name: Release Build

on:
  push:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
      
 release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: install Rust stable
        run: rustup install stable --profile minimal && rustup default stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./backend/"
          prefix-key: "rust-stable"
          key: ${{ matrix.targets.os }}
          shared-key: "release"

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      # - name: Delete current release assets
      #   uses: mknejp/delete-release-assets@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.event.release.tag_name }}
      #     fail-if-no-assets: false
      #     fail-if-no-release: false
      #     assets: |
      #       *.zip
      #       *.gz
      #       *.AppImage
      #       *.deb
      #       *.sig
      #       *.json

      - name: Install Dependencies (Ubuntu Only)
        if: startsWith(matrix.targets.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgtk-4-dev webkit2gtk-4.0 libwebkit2gtk-4.1* libappindicator3-dev librsvg2-dev patchelf openssl

      - name: Pnpm install and check
        run: |
          pnpm i
          pnpm check

      - name: Tauri build
        if: startsWith(matrix.targets.os, 'macos-') == false || matrix.targets.category != 'aarch64'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ github.event.release.id }}
          # tagName: ${{ github.event.release.tag_name }}
          # releaseName: "Clash Nyanpasu ${{ github.event.release.tag_name }}"
          # releaseBody: "More new features are now supported."
          # releaseDraft: false
          # prerelease: false
          tauriScript: pnpm tauri
          args: -f default-meta -c ./backend/tauri/tauri.conf.json

 release-update:
    needs: release
    runs-on: ubuntu-latest
    if: |
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Pnpm install
        run: pnpm i

      - name: Release updater file
        run: pnpm updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BODY: ${{ github.event.release.body }}
